#include "atlas/controller_runtime.hpp"
#include <algorithm>

namespace atlas {
ControllerRuntime::ControllerRuntime(IDisplayDriver& driver,IConfigurationStore& storage,INetworkStack& network,ILogger& logger,const PowerManager* power_manager)
    :driver_(driver),storage_(storage),network_(network),logger_(logger),power_manager_(power_manager){}
bool ControllerRuntime::boot(){const auto config=storage_.load_display();if(!config){logger_.info("factory provisioning");return false;}configuration_=*config;const auto caps=driver_.capabilities();const auto count=static_cast<std::size_t>(configuration_.width)*configuration_.height;if(count>caps.maximum_pixels||!driver_.initialize(configuration_)){status_.last_error="driver initialization failed";logger_.error(status_.last_error);return false;}status_.configured=true;const auto active=storage_.load_active_scene_id();if(active){const auto pixels=storage_.load_scene_frame(*active);if(pixels&&pixels->size()==count){FrameView frame{configuration_.width,configuration_.height,configuration_.color_model,255,*pixels};if(render(frame)){status_.playing=true;status_.active_scene_id=*active;++status_.rendered_frames;}}}return true;}
bool ControllerRuntime::compatible(const FrameView frame)const noexcept{return status_.configured&&frame.width==configuration_.width&&frame.height==configuration_.height&&frame.color_model==configuration_.color_model&&frame.pixels.size()==static_cast<std::size_t>(frame.width)*frame.height;}
bool ControllerRuntime::render(const FrameView frame){auto brightness=frame.brightness;if(power_manager_){const auto decision=power_manager_->evaluate(frame,configuration_.brightness);brightness=configuration_.brightness?static_cast<std::uint8_t>(std::min<std::uint16_t>(255,(static_cast<std::uint16_t>(decision.applied_brightness)*255)/configuration_.brightness)):0;status_.power_limited=decision.limited;status_.applied_frame_brightness=decision.applied_brightness;status_.estimated_current_milliamps=decision.estimated_milliamps;status_.estimated_power_milliwatts=decision.estimated_milliwatts;}return driver_.render({frame.width,frame.height,frame.color_model,brightness,frame.pixels});}
bool ControllerRuntime::receive_frame(const FrameView frame){if(!compatible(frame)){status_.last_error="invalid frame";return false;}if(!render(frame)){status_.last_error="render failed";return false;}++status_.rendered_frames;return true;}
bool ControllerRuntime::store_and_play(const std::string_view id,const FrameView frame){if(id.empty()||!compatible(frame)||!storage_.save_scene_frame(id,frame.pixels)||!storage_.save_active_scene_id(id)||!render(frame)){status_.last_error="scene persistence failed";return false;}status_.playing=true;status_.active_scene_id=id;++status_.rendered_frames;return true;}
bool ControllerRuntime::play_stored(const std::string_view id){const auto pixels=storage_.load_scene_frame(id);if(!pixels)return false;FrameView frame{configuration_.width,configuration_.height,configuration_.color_model,255,*pixels};if(!compatible(frame)||!render(frame)||!storage_.save_active_scene_id(id))return false;status_.playing=true;status_.active_scene_id=id;++status_.rendered_frames;return true;}
void ControllerRuntime::stop()noexcept{driver_.clear();status_.playing=false;}
bool ControllerRuntime::set_brightness(const std::uint8_t brightness){configuration_.brightness=brightness;return driver_.set_brightness(brightness);}
void ControllerRuntime::set_active_program(const std::string_view playlist_id,const std::string_view schedule_id){status_.active_playlist_id=playlist_id;status_.active_schedule_id=schedule_id;}
} // namespace atlas
