#include "atlas/local_api.hpp"
#include <cctype>
#include <cstdlib>
#include <utility>

namespace atlas { namespace {
std::string text(const std::vector<std::uint8_t>& value){return{value.begin(),value.end()};}
std::vector<std::uint8_t> bytes(const std::string& value){return{value.begin(),value.end()};}
std::string field(const std::string& json,const std::string& name){const auto key='"'+name+'"';auto at=json.find(key);if(at==std::string::npos)return{};at=json.find(':',at+key.size());if(at==std::string::npos)return{};++at;while(at<json.size()&&std::isspace(static_cast<unsigned char>(json[at])))++at;if(at<json.size()&&json[at]=='"'){const auto end=json.find('"',++at);return end==std::string::npos?std::string{}:json.substr(at,end-at);}const auto end=json.find_first_of(",}",at);return json.substr(at,end-at);}
bool decode_frame(const std::vector<std::uint8_t>& body,std::uint16_t& width,std::uint16_t& height,ColorModel& model,std::vector<Pixel>& pixels){if(body.size()<14||body[0]!='A'||body[1]!='T'||body[2]!='L'||body[3]!='F'||body[4]!=protocol_version)return false;width=static_cast<std::uint16_t>(body[5]|body[6]<<8);height=static_cast<std::uint16_t>(body[7]|body[8]<<8);if(body[9]>1)return false;model=body[9]==1?ColorModel::rgbw:ColorModel::rgb;const std::size_t channels=model==ColorModel::rgbw?4:3,count=static_cast<std::size_t>(width)*height;const std::uint32_t declared=static_cast<std::uint32_t>(body[10])|(static_cast<std::uint32_t>(body[11])<<8)|(static_cast<std::uint32_t>(body[12])<<16)|(static_cast<std::uint32_t>(body[13])<<24);if(count==0||count>maximum_pixels||declared!=count*channels||body.size()!=14+declared)return false;pixels.resize(count);std::size_t offset=14;for(auto& p:pixels){p={body[offset],body[offset+1],body[offset+2],channels==4?body[offset+3]:static_cast<std::uint8_t>(0)};offset+=channels;}return true;}
}
LocalApi::LocalApi(ControllerRuntime& runtime,IConfigurationStore& storage,ProvisioningManager& provisioning,DisplayConfiguration configuration,LocalAuthenticator* authenticator,OtaManager* ota):runtime_(runtime),storage_(storage),provisioning_(provisioning),configuration_(std::move(configuration)),authenticator_(authenticator),ota_(ota){}
ApiResponse LocalApi::json(const std::uint16_t status,std::string value)const{return{status,"application/json",bytes(value)};}
ApiResponse LocalApi::error(const std::uint16_t status,const std::string_view code,const std::string_view message)const{return json(status,"{\"protocolVersion\":1,\"accepted\":false,\"errorCode\":\""+std::string{code}+"\",\"message\":\""+std::string{message}+"\"}");}
ApiResponse LocalApi::handle(const ApiRequest& request){
 if(request.method==HttpMethod::get&&request.path=="/api/status"){const auto&s=runtime_.status();return json(200,"{\"protocolVersion\":1,\"configured\":"+std::string{s.configured?"true":"false"}+",\"playing\":"+(s.playing?"true":"false")+",\"activeSceneId\":\""+s.active_scene_id+"\",\"activePlaylistId\":\""+s.active_playlist_id+"\",\"activeScheduleId\":\""+s.active_schedule_id+"\",\"powerLimited\":"+(s.power_limited?"true":"false")+",\"appliedBrightness\":"+std::to_string(s.applied_frame_brightness)+",\"estimatedCurrentMilliamps\":"+std::to_string(s.estimated_current_milliamps)+",\"estimatedPowerMilliwatts\":"+std::to_string(s.estimated_power_milliwatts)+"}");}
 if(request.method==HttpMethod::get&&request.path=="/api/capabilities")return json(200,"{\"protocolVersion\":1,\"width\":"+std::to_string(configuration_.width)+",\"height\":"+std::to_string(configuration_.height)+",\"features\":[\"frames\",\"scenes\",\"playlists\",\"schedules\",\"storage\",\"provisioning\",\"powerLimit\"]}");
 if(request.method==HttpMethod::get&&request.path=="/api/config")return json(200,"{\"protocolVersion\":1,\"width\":"+std::to_string(configuration_.width)+",\"height\":"+std::to_string(configuration_.height)+",\"brightness\":"+std::to_string(configuration_.brightness)+"}");
 if(request.method!=HttpMethod::post)return error(404,"NotFound","Endpoint not found");
 if(authenticator_&&request.path!="/api/provision"){const auto authentication=authenticator_->authenticate(request.authentication_token);if(authentication==AuthenticationResult::locked)return error(429,"AuthenticationLocked","Too many authentication failures");if(authentication!=AuthenticationResult::accepted)return error(401,"Unauthorized","A valid local pairing token is required");}
 if(request.path=="/api/frame"){if(request.body.size()>maximum_frame_bytes)return error(413,"FrameTooLarge","Frame payload exceeds limit");std::vector<Pixel> pixels;std::uint16_t width{},height{};ColorModel model{ColorModel::rgb};if(!decode_frame(request.body,width,height,model,pixels))return error(400,"InvalidFrame","Frame is invalid or incompatible");const FrameView frame{width,height,model,255,pixels};if(!runtime_.receive_frame(frame))return error(400,"InvalidFrame","Frame is invalid or incompatible");return json(200,"{\"protocolVersion\":1,\"accepted\":true}");}
 if(request.path=="/api/scene"){if(request.scene_id.empty()||request.body.empty()||request.body.size()>maximum_scene_bytes)return error(413,"InvalidScene","Scene payload is invalid");return storage_.save_scene_blob(request.scene_id,request.body)?json(200,"{\"protocolVersion\":1,\"accepted\":true}"):error(507,"StorageFailure","Scene could not be stored");}
 if(request.path=="/api/play"){const auto id=field(text(request.body),"sceneId");return runtime_.play_stored(id)?json(200,"{\"protocolVersion\":1,\"accepted\":true}"):error(404,"SceneNotFound","Stored scene was not found");}
 if(request.path=="/api/stop"){runtime_.stop();return json(200,"{\"protocolVersion\":1,\"accepted\":true}");}
 if(request.path=="/api/brightness"){const auto value=field(text(request.body),"brightness");char* end=nullptr;const auto parsed=std::strtol(value.c_str(),&end,10);if(value.empty()||end==nullptr||*end!='\0'||parsed<0||parsed>255||!runtime_.set_brightness(static_cast<std::uint8_t>(parsed)))return error(400,"InvalidBrightness","Brightness must be between 0 and 255");return json(200,"{\"protocolVersion\":1,\"accepted\":true}");}
 if(request.path=="/api/provision"){const auto body=text(request.body);const auto result=provisioning_.submit({field(body,"ssid"),field(body,"password")});return result.accepted?json(200,"{\"protocolVersion\":1,\"accepted\":true,\"rebootRequired\":true}"):error(400,"ProvisioningFailed",result.error);}
 if(request.path=="/api/ota"){if(!ota_)return error(501,"OtaUnavailable","OTA is not configured");const auto result=ota_->stage(request.firmware_version,request.body,request.signature);switch(result){case OtaResult::accepted:return json(202,"{\"protocolVersion\":1,\"accepted\":true,\"rebootRequired\":true}");case OtaResult::too_large:return error(413,"FirmwareTooLarge","Firmware exceeds limit");case OtaResult::signature_rejected:return error(400,"FirmwareSignatureRejected","Firmware signature is invalid");case OtaResult::downgrade_rejected:return error(409,"FirmwareVersionRejected","Firmware version is already installed");case OtaResult::stage_failed:return error(500,"OtaStageFailed","Firmware could not be staged safely");default:return error(400,"InvalidFirmware","Firmware package is invalid");}}
 return error(404,"NotFound","Endpoint not found");
}
} // namespace atlas
