#include "atlas/native_drivers.hpp"
#include <algorithm>

namespace atlas { namespace {
std::uint8_t scale(std::uint8_t value, std::uint8_t brightness) { return static_cast<std::uint8_t>((static_cast<std::uint16_t>(value)*brightness+127)/255); }
bool valid_frame(const DisplayConfiguration& c, FrameView f, ColorModel model) { return f.width==c.width&&f.height==c.height&&f.color_model==model&&f.pixels.size()==static_cast<std::size_t>(c.width)*c.height; }
std::vector<Pixel> physical_pixels(const MatrixMapper&mapper,FrameView frame){std::vector<Pixel> result(frame.pixels.size());for(std::uint16_t y{};y<frame.height;++y)for(std::uint16_t x{};x<frame.width;++x)result[mapper.map(x,y).absolute_index]=frame.pixels[static_cast<std::size_t>(y)*frame.width+x];return result;}
void append_ordered(std::vector<std::uint8_t>& out, const Pixel& p, ChannelOrder order, std::uint8_t b) {
    const auto r=scale(p.r,b),g=scale(p.g,b),bl=scale(p.b,b),w=scale(p.w,b);
    switch(order){
    case ChannelOrder::rgb: out.insert(out.end(),{r,g,bl});break; case ChannelOrder::rbg:out.insert(out.end(),{r,bl,g});break;
    case ChannelOrder::grb:out.insert(out.end(),{g,r,bl});break; case ChannelOrder::gbr:out.insert(out.end(),{g,bl,r});break;
    case ChannelOrder::brg:out.insert(out.end(),{bl,r,g});break; case ChannelOrder::bgr:out.insert(out.end(),{bl,g,r});break;
    case ChannelOrder::rgbw:out.insert(out.end(),{r,g,bl,w});break; case ChannelOrder::grbw:out.insert(out.end(),{g,r,bl,w});break;
    case ChannelOrder::brgw:out.insert(out.end(),{bl,r,g,w});break; case ChannelOrder::wrgb:out.insert(out.end(),{w,r,g,bl});break;
    }
}
}
AddressableDriver::AddressableDriver(IAddressableTransport& t,AddressableProfile p):transport_(t),profile_(p){}
std::string_view AddressableDriver::id()const noexcept{return"generic.addressable";} DriverCapabilities AddressableDriver::capabilities()const noexcept{return{16'384,1,true,true,true};}
bool AddressableDriver::initialize(const DisplayConfiguration& c){if(c.width==0||c.height==0||c.color_model!=profile_.color_model||static_cast<std::size_t>(c.width)*c.height>capabilities().maximum_pixels)return false;try{mapper_=std::make_unique<MatrixMapper>(c);}catch(...){return false;}configuration_=c;brightness_=c.brightness;initialized_=transport_.configure(profile_.frequency_hz,profile_.reset_microseconds);return initialized_;}
bool AddressableDriver::set_brightness(std::uint8_t b){brightness_=b;return initialized_;}
bool AddressableDriver::render(FrameView f){if(!initialized_||!mapper_||!valid_frame(configuration_,f,profile_.color_model))return false;std::vector<std::uint8_t> bytes;bytes.reserve(f.pixels.size()*(profile_.color_model==ColorModel::rgbw?4:3));const auto b=scale(brightness_,f.brightness);for(const auto&p:physical_pixels(*mapper_,f))append_ordered(bytes,p,profile_.order,b);return transport_.transmit(bytes);}
void AddressableDriver::clear()noexcept{if(initialized_)transport_.transmit(std::vector<std::uint8_t>(static_cast<std::size_t>(configuration_.width)*configuration_.height*(profile_.color_model==ColorModel::rgbw?4:3)));} bool AddressableDriver::test(){if(!initialized_)return false;std::vector<Pixel> p(static_cast<std::size_t>(configuration_.width)*configuration_.height);if(!p.empty())p[0]={255,0,0,0};return render({configuration_.width,configuration_.height,profile_.color_model,255,p});}

ClockedDriver::ClockedDriver(IClockedTransport&t,ClockedProfile p):transport_(t),profile_(p){} std::string_view ClockedDriver::id()const noexcept{return"generic.clocked";} DriverCapabilities ClockedDriver::capabilities()const noexcept{return{65'536,1,true,false,true};}
bool ClockedDriver::initialize(const DisplayConfiguration&c){if(c.width==0||c.height==0||c.color_model!=ColorModel::rgb||static_cast<std::size_t>(c.width)*c.height>capabilities().maximum_pixels)return false;try{mapper_=std::make_unique<MatrixMapper>(c);}catch(...){return false;}configuration_=c;brightness_=c.brightness;initialized_=transport_.configure(profile_.frequency_hz);return initialized_;} bool ClockedDriver::set_brightness(std::uint8_t b){brightness_=b;return initialized_;}
bool ClockedDriver::render(FrameView f){if(!initialized_||!mapper_||!valid_frame(configuration_,f,ColorModel::rgb))return false;std::vector<std::uint8_t> bytes(4,0);bytes.reserve(8+f.pixels.size()*4+((f.pixels.size()+15)/16));const auto effective=scale(brightness_,f.brightness);const auto global=static_cast<std::uint8_t>((static_cast<std::uint16_t>(effective)*31+127)/255);for(const auto&p:physical_pixels(*mapper_,f))bytes.insert(bytes.end(),{static_cast<std::uint8_t>(0xE0|global),p.b,p.g,p.r});bytes.insert(bytes.end(),(f.pixels.size()+15)/16,0xFF);return transport_.transmit(bytes);} void ClockedDriver::clear()noexcept{if(!initialized_)return;std::vector<Pixel> p(static_cast<std::size_t>(configuration_.width)*configuration_.height);render({configuration_.width,configuration_.height,ColorModel::rgb,255,p});} bool ClockedDriver::test(){if(!initialized_)return false;std::vector<Pixel>p(static_cast<std::size_t>(configuration_.width)*configuration_.height);if(!p.empty())p[0]={255,255,255,0};return render({configuration_.width,configuration_.height,ColorModel::rgb,255,p});}

Hub75Driver::Hub75Driver(IHub75Transport&t):transport_(t){} std::string_view Hub75Driver::id()const noexcept{return"hub75";} DriverCapabilities Hub75Driver::capabilities()const noexcept{return{262'144,8,true,false,true};}
bool Hub75Driver::initialize(const DisplayConfiguration&c){if(c.width==0||c.height==0||c.color_model!=ColorModel::rgb||static_cast<std::size_t>(c.width)*c.height>capabilities().maximum_pixels)return false;try{mapper_=std::make_unique<MatrixMapper>(c);}catch(...){return false;}configuration_=c;brightness_=c.brightness;initialized_=transport_.configure(c.width,c.height);return initialized_;} bool Hub75Driver::set_brightness(std::uint8_t b){brightness_=b;return initialized_;} bool Hub75Driver::render(FrameView f){if(!initialized_||!mapper_||!valid_frame(configuration_,f,ColorModel::rgb))return false;return transport_.present(physical_pixels(*mapper_,f),scale(brightness_,f.brightness));} void Hub75Driver::clear()noexcept{if(initialized_)transport_.present(std::vector<Pixel>(static_cast<std::size_t>(configuration_.width)*configuration_.height),brightness_);} bool Hub75Driver::test(){if(!initialized_)return false;std::vector<Pixel>p(static_cast<std::size_t>(configuration_.width)*configuration_.height);if(!p.empty())p[0]={255,0,0,0};return render({configuration_.width,configuration_.height,ColorModel::rgb,255,p});}
} // namespace atlas
