#include "atlas/controller_runtime.hpp"
#include "atlas/driver_registry.hpp"
#include "atlas/matrix_mapper.hpp"
#include "atlas/local_api.hpp"
#include "atlas/native_drivers.hpp"
#include "atlas/playlist_scheduler.hpp"
#include <cassert>
#include <algorithm>
#include <map>

using namespace atlas;
namespace {
class Driver final:public IDisplayDriver{public:bool initialized{},cleared{};std::uint8_t frame_brightness{};std::vector<Pixel> last;std::string_view id()const noexcept override{return"test";}DriverCapabilities capabilities()const noexcept override{return{1024,1,true,true,true};}bool initialize(const DisplayConfiguration&)override{initialized=true;return true;}bool set_brightness(std::uint8_t)override{return true;}bool render(FrameView f)override{frame_brightness=f.brightness;last.assign(f.pixels.begin(),f.pixels.end());return true;}void clear()noexcept override{cleared=true;}bool test()override{return true;}};
class Store final:public IConfigurationStore{public:DisplayConfiguration config;std::string active,active_playlist;std::map<std::string,std::vector<Pixel>> scenes;std::map<std::string,std::vector<std::uint8_t>> blobs;std::vector<Playlist>playlists;std::vector<Schedule>schedules;std::optional<NetworkCredentials>credentials;std::optional<DisplayConfiguration>load_display()override{return config.width?std::optional<DisplayConfiguration>{config}:std::nullopt;}bool save_display(const DisplayConfiguration&c)override{config=c;return true;}std::optional<std::string>load_active_scene_id()override{return active.empty()?std::nullopt:std::optional<std::string>{active};}bool save_active_scene_id(std::string_view id)override{active=id;return true;}std::optional<std::vector<Pixel>>load_scene_frame(std::string_view id)override{auto i=scenes.find(std::string{id});return i==scenes.end()?std::nullopt:std::optional<std::vector<Pixel>>{i->second};}bool save_scene_frame(std::string_view id,const std::vector<Pixel>&p)override{scenes[std::string{id}]=p;return true;}std::optional<NetworkCredentials>load_network()override{return credentials;}bool save_network(const NetworkCredentials&value)override{credentials=value;return true;}bool clear_network()override{credentials.reset();return true;}bool save_scene_blob(std::string_view id,const std::vector<std::uint8_t>&value)override{blobs[std::string{id}]=value;return true;}std::optional<std::vector<std::uint8_t>>load_scene_blob(std::string_view id)override{auto i=blobs.find(std::string{id});return i==blobs.end()?std::nullopt:std::optional<std::vector<std::uint8_t>>{i->second};}std::vector<Playlist>load_playlists()override{return playlists;}bool save_playlist(const Playlist&p)override{auto i=std::find_if(playlists.begin(),playlists.end(),[&p](const auto&v){return v.id==p.id;});if(i==playlists.end())playlists.push_back(p);else*i=p;return true;}std::vector<Schedule>load_schedules()override{return schedules;}bool save_schedule(const Schedule&s)override{auto i=std::find_if(schedules.begin(),schedules.end(),[&s](const auto&v){return v.id==s.id;});if(i==schedules.end())schedules.push_back(s);else*i=s;return true;}std::optional<std::string>load_active_playlist_id()override{return active_playlist.empty()?std::nullopt:std::optional<std::string>{active_playlist};}bool save_active_playlist_id(std::string_view id)override{active_playlist=id;return true;}};
class Network final:public INetworkStack{public:bool ap{},station{},can_connect{true};NetworkCredentials configured;bool configure_station(const NetworkCredentials&value)override{configured=value;return true;}bool start_station()override{station=can_connect;return station;}bool start_access_point()override{ap=true;return true;}bool connected()const noexcept override{return station;}};
class Log final:public ILogger{public:void info(std::string_view)noexcept override{}void error(std::string_view)noexcept override{}};
class AddressableTransport final:public IAddressableTransport{public:std::uint32_t frequency{};std::uint16_t reset{};std::vector<std::uint8_t>bytes;bool configure(std::uint32_t f,std::uint16_t r)override{frequency=f;reset=r;return true;}bool transmit(const std::vector<std::uint8_t>&v)override{bytes=v;return true;}};
class ClockedTransport final:public IClockedTransport{public:std::uint32_t frequency{};std::vector<std::uint8_t>bytes;bool configure(std::uint32_t f)override{frequency=f;return true;}bool transmit(const std::vector<std::uint8_t>&v)override{bytes=v;return true;}};
class Hub75Transport final:public IHub75Transport{public:std::uint16_t width{},height{};std::uint8_t brightness{};std::vector<Pixel>pixels;bool configure(std::uint16_t w,std::uint16_t h)override{width=w;height=h;return true;}bool present(const std::vector<Pixel>&p,std::uint8_t b)override{pixels=p;brightness=b;return true;}};
class SchedulerClock final:public ISchedulerClock{public:std::uint64_t now{};std::uint8_t day{};std::uint16_t minute{};bool synced{true};std::uint64_t milliseconds()const noexcept override{return now;}std::uint8_t weekday()const noexcept override{return day;}std::uint16_t minute_of_day()const noexcept override{return minute;}bool synchronized()const noexcept override{return synced;}};
class CredentialVault final:public INetworkCredentialVault{public:std::optional<NetworkCredentials>value;std::optional<NetworkCredentials>load()override{return value;}bool save(const NetworkCredentials&v)override{value=v;return true;}bool clear()override{value.reset();return true;}};
DisplayConfiguration config(){return{4,2,ColorModel::rgb,ChannelOrder::grb,255,{{0,0,4,2,Origin::top_left,Traversal::row,Layout::serpentine}}};}
}
int main(){
    MatrixMapper mapper{config()};assert(mapper.map(0,0).absolute_index==0);assert(mapper.map(3,1).absolute_index==4);
    std::vector<Pixel> pixels(8);pixels[3+4]={10,20,30,0};auto bytes=mapper.encode({4,2,ColorModel::rgb,255,pixels});assert(bytes[12]==20&&bytes[13]==10&&bytes[14]==30);
    Store store;store.config=config();Driver driver;Network network;Log log;ControllerRuntime runtime{driver,store,network,log};assert(runtime.boot());assert(driver.initialized);
    pixels[0]={255,0,0,0};assert(runtime.store_and_play("scene-1",{4,2,ColorModel::rgb,255,pixels}));assert(runtime.status().playing);runtime.stop();assert(driver.cleared);
    Driver restarted_driver;ControllerRuntime restarted{restarted_driver,store,network,log};assert(restarted.boot());assert(restarted.status().playing&&restarted.status().active_scene_id=="scene-1");
    ProvisioningManager provisioning{store,network,log};assert(provisioning.boot()&&provisioning.state()==ProvisioningState::access_point);auto provisioned=provisioning.submit({"Negocio","password123"});assert(provisioned.accepted&&network.station&&store.credentials.has_value());
    Store secure_store;CredentialVault vault;Network secure_network;ProvisioningManager secure_provisioning{secure_store,secure_network,log,&vault};assert(secure_provisioning.boot());assert(secure_provisioning.submit({"SecureLAN","password123"}).accepted&&vault.value.has_value()&&!secure_store.credentials.has_value());
    LocalApi api{runtime,store,provisioning,config()};assert(api.handle({HttpMethod::get,"/api/status",{}, {}}).status==200);assert(api.handle({HttpMethod::post,"/api/brightness",{'{','\"','b','r','i','g','h','t','n','e','s','s','\"',':','1','2','8','}'},{}}).status==200);
    std::vector<std::uint8_t> frame(14+24);frame[0]='A';frame[1]='T';frame[2]='L';frame[3]='F';frame[4]=1;frame[5]=4;frame[7]=2;frame[10]=24;frame[14]=255;
    assert(api.handle({HttpMethod::post,"/api/frame",frame,{}}).status==200);frame[10]=23;assert(api.handle({HttpMethod::post,"/api/frame",frame,{}}).status==400);
    const std::vector<std::uint8_t> scene{'{','}'};assert(api.handle({HttpMethod::post,"/api/scene",scene,"scene-json"}).status==200&&store.blobs.count("scene-json")==1);
    assert(api.handle({HttpMethod::post,"/api/scene",{},"bad"}).status==413);assert(api.handle({HttpMethod::get,"/missing",{}, {}}).status==404);
    AddressableTransport addressable_transport;AddressableDriver ws2812{addressable_transport,ws2812b_profile};auto rgb_config=config();assert(ws2812.initialize(rgb_config));std::vector<Pixel>driver_pixels(8);driver_pixels[0]={10,20,30,0};assert(ws2812.render({4,2,ColorModel::rgb,255,driver_pixels}));assert(addressable_transport.frequency==800000&&addressable_transport.bytes[0]==20&&addressable_transport.bytes[1]==10&&addressable_transport.bytes[2]==30);
    AddressableDriver sk6812{addressable_transport,sk6812_rgbw_profile};auto rgbw_config=config();rgbw_config.color_model=ColorModel::rgbw;assert(sk6812.initialize(rgbw_config));driver_pixels[0]={1,2,3,4};assert(sk6812.render({4,2,ColorModel::rgbw,255,driver_pixels}));assert(addressable_transport.bytes.size()==32&&addressable_transport.bytes[0]==2&&addressable_transport.bytes[3]==4);
    ClockedTransport clocked_transport;ClockedDriver apa102{clocked_transport,apa102_profile};assert(apa102.initialize(rgb_config));assert(apa102.render({4,2,ColorModel::rgb,255,driver_pixels}));assert(clocked_transport.frequency==8000000&&clocked_transport.bytes.size()==37&&clocked_transport.bytes[4]==0xFF&&clocked_transport.bytes[5]==3&&clocked_transport.bytes[6]==2&&clocked_transport.bytes[7]==1);
    Hub75Transport hub75_transport;Hub75Driver hub75{hub75_transport};assert(hub75.initialize(rgb_config));assert(hub75.render({4,2,ColorModel::rgb,128,driver_pixels}));assert(hub75_transport.width==4&&hub75_transport.height==2&&hub75_transport.pixels[0]==driver_pixels[0]&&hub75_transport.brightness==128);
    std::vector<Pixel> white(8,Pixel{255,255,255,0});PowerManager power{{5000,200,50,255,20}};const auto decision=power.evaluate({4,2,ColorModel::rgb,255,white},255);assert(decision.limited&&decision.budget_milliamps==150&&decision.estimated_milliamps<=150&&decision.estimated_milliwatts<=750);
    PowerManager no_pixel_budget{{5000,100,200,255,20}};assert(no_pixel_budget.evaluate({4,2,ColorModel::rgb,255,white},255).applied_brightness==0);std::vector<Pixel> rgbw_white(1,Pixel{255,255,255,255});PowerManager rgbw_power{{5000,1000,0,128,20}};const auto rgbw_decision=rgbw_power.evaluate({1,1,ColorModel::rgbw,255,rgbw_white},255);assert(!rgbw_decision.limited&&rgbw_decision.requested_brightness==128&&rgbw_decision.estimated_milliamps==40);
    Store limited_store;limited_store.config=config();Driver limited_driver;ControllerRuntime limited_runtime{limited_driver,limited_store,network,log,&power};assert(limited_runtime.boot());assert(limited_runtime.receive_frame({4,2,ColorModel::rgb,255,white}));assert(limited_runtime.status().power_limited&&limited_runtime.status().estimated_current_milliamps<=150&&limited_driver.frame_brightness<255);
    Store schedule_store;schedule_store.config=config();schedule_store.scenes["morning"]=std::vector<Pixel>(8,Pixel{255,0,0,0});schedule_store.scenes["evening"]=std::vector<Pixel>(8,Pixel{0,0,255,0});Driver schedule_driver;ControllerRuntime schedule_runtime{schedule_driver,schedule_store,network,log};assert(schedule_runtime.boot());SchedulerClock scheduler_clock;PlaylistScheduler scheduler{schedule_runtime,schedule_store,scheduler_clock};assert(scheduler.boot());assert(!scheduler.save({"bad",{{"morning",0}},true}));assert(scheduler.save({"daily",{{"morning",1000},{"evening",2000}},true}));assert(scheduler.play("daily")&&schedule_runtime.status().active_scene_id=="morning");scheduler_clock.now=1000;assert(scheduler.tick()&&schedule_runtime.status().active_scene_id=="evening");
    assert(scheduler.save({"business-hours","daily",1u<<1,60,120,5,true}));assert(scheduler.save({"overnight","daily",1u<<1,1380,60,9,true}));scheduler_clock.day=1;scheduler_clock.minute=90;PlaylistScheduler scheduled_restart{schedule_runtime,schedule_store,scheduler_clock};assert(scheduled_restart.boot()&&scheduled_restart.active_schedule_id()=="business-hours");scheduler_clock.day=2;scheduler_clock.minute=30;assert(scheduled_restart.tick()&&scheduled_restart.active_schedule_id()=="overnight"&&schedule_runtime.status().active_playlist_id=="daily");
    scheduler_clock.synced=false;scheduler_clock.now+=1000;assert(scheduled_restart.tick()&&scheduled_restart.active_schedule_id()=="overnight");
    DriverRegistry registry;assert(registry.register_driver("generic.addressable",[&addressable_transport](){return std::make_unique<AddressableDriver>(addressable_transport,ws2812b_profile);}));assert(registry.register_driver("generic.clocked",[&clocked_transport](){return std::make_unique<ClockedDriver>(clocked_transport,apa102_profile);}));assert(registry.register_driver("hub75",[&hub75_transport](){return std::make_unique<Hub75Driver>(hub75_transport);}));assert(registry.size()==3&&registry.create("hub75")->id()=="hub75"&&registry.create("missing")==nullptr);return 0;
}
