#include "atlas/local_api.hpp"
#include "atlas/native_drivers.hpp"
#include "atlas/playlist_scheduler.hpp"
#include <algorithm>
#include <cassert>
#include <map>

using namespace atlas;
namespace {
class Store final:public IConfigurationStore{
public:DisplayConfiguration config;std::string active_scene,active_playlist;std::map<std::string,std::vector<Pixel>>frames;std::map<std::string,std::vector<std::uint8_t>>blobs;std::vector<Playlist>playlists;std::vector<Schedule>schedules;std::optional<NetworkCredentials>network;
std::optional<DisplayConfiguration>load_display()override{return config.width?std::optional<DisplayConfiguration>{config}:std::nullopt;}bool save_display(const DisplayConfiguration&v)override{config=v;return true;}std::optional<std::string>load_active_scene_id()override{return active_scene.empty()?std::nullopt:std::optional<std::string>{active_scene};}bool save_active_scene_id(std::string_view v)override{active_scene=v;return true;}std::optional<std::vector<Pixel>>load_scene_frame(std::string_view id)override{auto i=frames.find(std::string{id});return i==frames.end()?std::nullopt:std::optional<std::vector<Pixel>>{i->second};}bool save_scene_frame(std::string_view id,const std::vector<Pixel>&v)override{frames[std::string{id}]=v;return true;}std::optional<NetworkCredentials>load_network()override{return network;}bool save_network(const NetworkCredentials&v)override{network=v;return true;}bool clear_network()override{network.reset();return true;}bool save_scene_blob(std::string_view id,const std::vector<std::uint8_t>&v)override{blobs[std::string{id}]=v;return true;}std::optional<std::vector<std::uint8_t>>load_scene_blob(std::string_view id)override{auto i=blobs.find(std::string{id});return i==blobs.end()?std::nullopt:std::optional<std::vector<std::uint8_t>>{i->second};}std::vector<Playlist>load_playlists()override{return playlists;}bool save_playlist(const Playlist&v)override{playlists.push_back(v);return true;}std::vector<Schedule>load_schedules()override{return schedules;}bool save_schedule(const Schedule&v)override{schedules.push_back(v);return true;}std::optional<std::string>load_active_playlist_id()override{return active_playlist.empty()?std::nullopt:std::optional<std::string>{active_playlist};}bool save_active_playlist_id(std::string_view v)override{active_playlist=v;return true;}
};
class Network final:public INetworkStack{public:bool ap{},station{},available{true};NetworkCredentials value;bool configure_station(const NetworkCredentials&v)override{value=v;return true;}bool start_station()override{return station=available;}bool start_access_point()override{ap=true;return true;}bool connected()const noexcept override{return station;}};
class Transport final:public IAddressableTransport{public:std::vector<std::uint8_t>bytes;bool configure(std::uint32_t,std::uint16_t)override{return true;}bool transmit(const std::vector<std::uint8_t>&v)override{bytes=v;return true;}};
class Log final:public ILogger{public:void info(std::string_view)noexcept override{}void error(std::string_view)noexcept override{}};
class Clock final:public ISchedulerClock{public:std::uint64_t ms{};std::uint8_t day{1};std::uint16_t minute{600};bool milliseconds_synced{true};std::uint64_t milliseconds()const noexcept override{return ms;}std::uint8_t weekday()const noexcept override{return day;}std::uint16_t minute_of_day()const noexcept override{return minute;}bool synchronized()const noexcept override{return milliseconds_synced;}};
class Verifier final:public IFirmwareVerifier{public:bool valid{true};bool verify(const std::vector<std::uint8_t>&,const std::vector<std::uint8_t>&)override{return valid;}};class OtaPlatform final:public IOtaPlatform{public:bool can_install(std::string_view)const override{return true;}bool stage(const std::vector<std::uint8_t>&,std::string_view)override{return true;}bool activate_on_reboot()override{return true;}bool confirm_running()override{return true;}void rollback()noexcept override{}};
DisplayConfiguration configuration(){return{4,2,ColorModel::rgb,ChannelOrder::grb,255,{{0,0,4,2,Origin::top_left,Traversal::row,Layout::serpentine}}};}
std::vector<std::uint8_t> frame_payload(){std::vector<std::uint8_t>v(14+24);v[0]='A';v[1]='T';v[2]='L';v[3]='F';v[4]=1;v[5]=4;v[7]=2;v[10]=24;const auto logical=(1*4+3)*3;v[14+logical]=10;v[15+logical]=20;v[16+logical]=30;return v;}
std::vector<std::uint8_t> json(std::string_view v){return{v.begin(),v.end()};}
}
int main(){
    Store store;store.config=configuration();Network network;Log log;Transport transport;AddressableDriver driver{transport,ws2812b_profile};PowerManager power{{5000,10000,500,255,20}};ControllerRuntime runtime{driver,store,network,log,&power};assert(runtime.boot());ProvisioningManager provisioning{store,network,log};assert(provisioning.boot()&&network.ap);assert(provisioning.submit({"AtlasLAN","password123"}).accepted&&network.connected());
    LocalApi api{runtime,store,provisioning,store.config};assert(api.handle({HttpMethod::get,"/api/capabilities",{}, {}}).status==200);assert(api.handle({HttpMethod::get,"/api/config",{}, {}}).status==200);auto payload=frame_payload();assert(api.handle({HttpMethod::post,"/api/frame",payload,{}}).status==200);assert(transport.bytes.size()==24);const auto physical=4*3;assert(transport.bytes[physical]==20&&transport.bytes[physical+1]==10&&transport.bytes[physical+2]==30);
    payload[4]=99;assert(api.handle({HttpMethod::post,"/api/frame",payload,{}}).status==400);assert(api.handle({HttpMethod::post,"/api/brightness",json("{\"brightness\":128}"),{}}).status==200);payload=frame_payload();assert(api.handle({HttpMethod::post,"/api/frame",payload,{}}).status==200&&transport.bytes[physical]==10);assert(api.handle({HttpMethod::post,"/api/scene",json("compiled-scene"),"offer"}).status==200&&store.blobs.count("offer")==1);
    std::vector<Pixel>offer(8);offer[7]={10,20,30,0};std::vector<Pixel>closed(8);closed[0]={0,0,255,0};assert(store.save_scene_frame("offer",offer)&&store.save_scene_frame("closed",closed));assert(api.handle({HttpMethod::post,"/api/play",json("{\"sceneId\":\"offer\"}"),{}}).status==200);assert(runtime.status().active_scene_id=="offer");assert(api.handle({HttpMethod::post,"/api/stop",{}, {}}).status==200&&std::all_of(transport.bytes.begin(),transport.bytes.end(),[](auto v){return v==0;}));
    Clock clock;PlaylistScheduler scheduler{runtime,store,clock};assert(scheduler.boot());assert(scheduler.save({"business",{{"offer",1000},{"closed",1000}},true}));assert(scheduler.save({"weekday","business",1u<<1,540,1020,1,true}));assert(scheduler.tick()&&runtime.status().active_scene_id=="offer");clock.ms=1000;assert(scheduler.tick()&&runtime.status().active_scene_id=="closed");
    network.available=false;network.station=false;Transport restarted_transport;AddressableDriver restarted_driver{restarted_transport,ws2812b_profile};ControllerRuntime restarted{restarted_driver,store,network,log,&power};assert(restarted.boot()&&restarted.status().playing&&restarted.status().active_scene_id=="closed");PlaylistScheduler restarted_scheduler{restarted,store,clock};assert(restarted_scheduler.boot()&&restarted_scheduler.active_playlist_id()=="business");assert(!network.connected()&&restarted.status().playing);
    network.available=true;ProvisioningManager reconnect{store,network,log};assert(reconnect.boot()&&network.connected());LocalAuthenticator authentication{"device-token",clock};Verifier verifier;OtaPlatform ota_platform;OtaManager ota{verifier,ota_platform};LocalApi secured_api{restarted,store,reconnect,store.config,&authentication,&ota};assert(secured_api.handle({HttpMethod::post,"/api/stop",{}, {}}).status==401);assert(secured_api.handle({HttpMethod::post,"/api/stop",{}, {},"device-token"}).status==200);verifier.valid=false;assert(secured_api.handle({HttpMethod::post,"/api/ota",{1,2,3},{},"device-token",{9},"2.0.0"}).status==400);verifier.valid=true;assert(secured_api.handle({HttpMethod::post,"/api/ota",{1,2,3},{},"device-token",{9},"2.0.0"}).status==202);return 0;
}
