#include "atlas/ota_recovery.hpp"
#include "atlas/security.hpp"
#include <cassert>

using namespace atlas;
namespace {
class Clock final:public IClock{public:std::uint64_t now{};std::uint64_t milliseconds()const noexcept override{return now;}};
class Verifier final:public IFirmwareVerifier{public:bool valid{true};bool verify(const std::vector<std::uint8_t>&,const std::vector<std::uint8_t>&)override{return valid;}};
class OtaPlatform final:public IOtaPlatform{public:bool newer{true},staged{},activated{},confirmed{},rolled_back{};bool can_install(std::string_view)const override{return newer;}bool stage(const std::vector<std::uint8_t>&,std::string_view)override{return staged=true;}bool activate_on_reboot()override{return activated=true;}bool confirm_running()override{return confirmed=true;}void rollback()noexcept override{rolled_back=true;}};
class RecoveryPlatform final:public IRecoveryPlatform{public:bool backed{},restored{},safe{};std::uint8_t failures{};bool backup_configuration()override{return backed=true;}bool restore_configuration()override{return restored=true;}std::uint8_t boot_failures()const noexcept override{return failures;}void set_boot_failures(std::uint8_t v)noexcept override{failures=v;}void enter_safe_mode()noexcept override{safe=true;}};
class Entropy final:public IEntropySource{public:bool fill(std::vector<std::uint8_t>&bytes)override{for(std::size_t i{};i<bytes.size();++i)bytes[i]=static_cast<std::uint8_t>(i);return true;}};class IdentityStore final:public IDeviceIdentityStore{public:std::optional<DeviceIdentity>identity;std::optional<DeviceIdentity>load_identity()override{return identity;}bool save_identity(const DeviceIdentity&value)override{identity=value;return true;}};
}
int main(){
    Entropy entropy;IdentityStore identity_store;DeviceIdentityManager identities{identity_store,entropy};const auto identity=identities.ensure();assert(identity&&identity->id=="atlas-000102030405060708090a0b0c0d0e0f"&&identity->host_name=="atlas-00010203");assert(identities.ensure()->id==identity->id);const auto token=DeviceIdentityManager::create_pairing_token(entropy);assert(token&&token->size()==64);
    Clock clock;LocalAuthenticator authentication{"secret-device-token",clock,3,1000};assert(authentication.authenticate({})==AuthenticationResult::missing);assert(authentication.authenticate("wrong")==AuthenticationResult::invalid);assert(authentication.authenticate("wrong")==AuthenticationResult::invalid);assert(authentication.authenticate("wrong")==AuthenticationResult::locked);assert(authentication.authenticate("secret-device-token")==AuthenticationResult::locked);clock.now=1000;assert(authentication.authenticate("secret-device-token")==AuthenticationResult::accepted);
    Verifier verifier;OtaPlatform platform;OtaManager ota{verifier,platform};const std::vector<std::uint8_t>image{1,2,3},signature{9,8};verifier.valid=false;assert(ota.stage("2.0.0",image,signature)==OtaResult::signature_rejected&&!platform.staged);verifier.valid=true;platform.newer=false;assert(ota.stage("1.0.0",image,signature)==OtaResult::downgrade_rejected);platform.newer=true;assert(ota.stage("2.0.0",image,signature)==OtaResult::accepted&&platform.staged&&platform.activated);assert(!ota.confirm_boot(false)&&platform.rolled_back);platform.rolled_back=false;assert(ota.confirm_boot(true)&&platform.confirmed&&!platform.rolled_back);
    RecoveryPlatform recovery_platform;RecoveryManager recovery{recovery_platform,3};assert(recovery.backup()&&recovery_platform.backed);assert(!recovery.record_boot(false)&&recovery_platform.failures==1);assert(!recovery.record_boot(false)&&recovery_platform.failures==2);assert(recovery.record_boot(false)&&recovery_platform.restored&&recovery_platform.safe&&recovery_platform.failures==0);recovery_platform.failures=2;assert(recovery.record_boot(true)&&recovery_platform.failures==0);return 0;
}
